DELETE http://localhost:5050/posts/296xqz773X37kDQvHhiA8pJf0lQ
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTI0NTUxNjIsInVzZXJJZCI6IjI5NEkzc042SlVCczNEUXl3WnJQZzFPQUFJdyJ9.9nSA-3AdpaniM8CYojPkPH3AQULDTAU_P3epXbrCfLE
