POST http://localhost:5050/posts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTI2NDc1ODEsInVzZXJJZCI6IjI5NEkzc042SlVCczNEUXl3WnJQZzFPQUFJdyJ9.-Fp3AZUfyzYM4Q-j2eGhwLvsqh_MdEyDTvLIOxvHbPU

{
  "postContent": "Contenido de mi post 1"
}