# Correct Authorization
GET http://localhost:5050/me
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTI0NTEwMTIsInVzZXJJZCI6IjI5NEkzc042SlVCczNEUXl3WnJQZzFPQUFJdyJ9.w73EBwE7Ahvx2qCn4wkh9uFfG00_wIyuoGlvghmQCes
